schemaVersion: 2.3.0
metadata:
  name: jumpstarter-devspace
  icon: https://jumpstarter.dev/jumpstarter.svg
  tags:
    - Python
    - Jumpstarter
  language: Python
projects:
  - name: jumpstarter
    git:
      remotes:
        origin: https://github.com/mangelajo/jumpstarter-kc25-devspace.git
components:
  - name: runtime
    container:
      image: quay.io/mangelajo/kubecon-jumpstarter-devspace:latest
      mountSources: true
      env: # use insecure TLS connection for now, you can remove this if your jumpstarter deployment has trusted TLS certs
        - name: JUMPSTARTER_GRPC_INSECURE
          value: "1"
        - name: CARGO_HOME
          value: $(PROJECTS_ROOT)/cargo
      memoryLimit: 4Gi
      memoryRequest: 1Gi
      cpuRequest: 100m
      cpuLimit: 4

commands:
  - id: pytest
    exec:
      component: runtime
      commandLine: pytest

  - id: client-list
    exec:
      component: runtime
      commandLine: jmp config client list

  - id: list-my-leases
    exec:
      component: runtime
      commandLine: jmp get leases

  - id: release-my-leases
    exec:
      component: runtime
      commandLine: jmp delete leases --all

  - id: list-exporters
    exec:
      component: runtime
      commandLine: jmp get exporters
